### ISSUE TITLE
Resizing issues

### ISSUE THREAD

**Issue by AgentFeeble** [RidgeCorn/RCPageControl#1]
I'm having a few issues when the page control is resized, or the frame is changed at all for that matter. When my view controller auto rotates, the frame of the page control is animated to a different value, and the selected dot disappears. I have tracked the issue down to the `- (void)_refreshIndicator:(BOOL)forceRefresh` method. If I reset each dots transform, the view animates correctly. This is the relevant code snippet that works for me

```
- (void)_refreshIndicator:(BOOL)forceRefresh {
    if ( !(_hidesForSinglePage && _numberOfPages <= 1)) {
        [self setHidden:NO];

        if (forceRefresh || self.subviews.count != _numberOfPages) {
            CGPoint position = [self positionForNumberOfPages:self.numberOfPages];

            NSInteger index = 0;

            for (; index < _numberOfPages; index ++) {
                CGRect frame = CGRectMake(position.x + index * (_indicatorDotGap + _indicatorDotWidth), position.y, _indicatorDotWidth, _indicatorDotWidth);
                UIView *dot = [self _dotAtIndex:index] ?: [[UIView alloc] initWithFrame:frame];


                // This line fixes the problem
                [dot setTransform:CGAffineTransformIdentity];


                [dot setTag:[self _dotTagAtIndex:index]];
                [dot setBackgroundColor:_pageIndicatorTintColor];
                [dot.layer setMasksToBounds:YES];
                [dot.layer setCornerRadius:dot.frame.size.height / 2];

                if ( !dot.superview) {
                    [self addSubview:dot];
                } else {
                    [dot setFrame:frame];
                }
...
```

Also, a minor annoyance is the logging of the frame in the `- (void)setFrame:` method. It would be nice if you could remove that so the console output doesn't get polluted when ever my view rotates. 

Besides all of that, nice work on the control :)

**Comment by AgentFeeble** [comment]
I just realised that the fix above creates another issue. If the frame is changed inside an animation block, then resetting the transform to the identity like that creates an animation of the transform property, so the selected dot animates from large back to its normal size. 

But thats easy to fix, if you disable animations before setting the transform

```
[UIView performWithoutAnimation:^
{
    [dot setTransform:CGAffineTransformIdentity];
}];
```

or, if you want to maintain your iOS 6.0 build target

```
BOOL reenableAnimations = [UIView areAnimationsEnabled];
[UIView setAnimationsEnabled:NO];
[dot setTransform:CGAffineTransformIdentity];
[UIView setAnimationsEnabled:reenableAnimations];
```

**Comment by looping** [comment]
Thanks, @AgentFeeble, very nice work  :+1: 
Please check out the latest commit 262ff55d3de3b978249b71d5d1eb98fce75d5429. I will release `v0.1.1` after Apple release `WATCH` :D 
Let me know if I missed something.
