### ISSUE TITLE
Pop.h file not found

### ISSUE THREAD

**Issue by yusadogru** [RidgeCorn/RCPageControl#3]
I have a problem with <pop.h>
not working this like
![screen shot 2017-06-08 at 11 24 02 am](https://user-images.githubusercontent.com/19792753/26919110-390c299c-4c3d-11e7-8fe0-7a0358a4a20c.png)
but working in quotes "pop.h"
![screen shot 2017-06-08 at 11 24 14 am](https://user-images.githubusercontent.com/19792753/26919175-7a758d60-4c3d-11e7-8eed-e5d1b83c65b2.png)
Can you fix it in pod file? or this issue at only me

**Comment by looping** [comment]
Hi, I can't reproduce this issue.
Can you provide more information about this?  Like CocoaPods version, and Xcode version.
Or you should use latest released version and try again.
